#!/bin/bash

LOCAL_FOLDER=../
USER=pi
POST_NET=192.168.30
POST_START=199
POST_END=199
REMOTE_FOLDER=/home/pi/python/
REMOTE_MAIN=main.py

REMOVE_MASK=*.pyc
RUN=-r
ARGS=$1


for ((post=$POST_START; post<=$POST_END; post++))
do
    rsync -avzu --exclude={.tags,*.pyc,*.log,*.log.*,*.orig,*.conf} --progress --delete $LOCAL_FOLDER -e ssh $USER@$POST_NET.$post:$REMOTE_FOLDER
ssh $USER@$POST_NET.$post << EOF
killall -9 python
killall -9 omxplayer.bin
killall Uniteller.Framework.Kernel.ConsoleHost.a
killall -9 Uniteller.Frame
rm $REMOTE_FOLDER$REMOVE_MASK
EOF
done
echo $ARGS

if [[ "$ARGS" == "$RUN" ]];
then
for ((post=$POST_START; post<=$POST_END; post++))
do
ssh $USER@$POST_NET.$post << EOF
export DISPLAY=:0.0
$REMOTE_FOLDER$REMOTE_MAIN &
EOF
done
fi


