#!/bin/bash

LOCAL_FOLDER=../
USER=pi
POST_NET=10.0.10
POST_START=101
POST_END=101
REMOTE_FOLDER=/home/pi/test_tereshko/
SYNC_FILE_CONFIG=config/terminal101_test.cfg
REMOTE_MAIN=main.py

REMOVE_MASK=*.pyc
RUN=-r
ARGS=$1


for ((post=$POST_START; post<=$POST_END; post++))
do
    # обратная синхронизация. Передаються файлы конфига с терминала в конфиг проекта
    rsync -avzu -e ssh $USER@$POST_NET.$post:$REMOTE_FOLDER$SYNC_FILE_CONFIG $LOCAL_FOLDER$SYNC_FILE_CONFIG
    # с локального проекта в удаленный репозиторий
    rsync -avzu --exclude={.tags,*.pyc,*.log,*.log.*,*.orig,*.conf,*.pickle} --progress --delete $LOCAL_FOLDER -e ssh $USER@$POST_NET.$post:$REMOTE_FOLDER
ssh $USER@$POST_NET.$post << EOF
killall -9 python
killall -9 omxplayer.bin
rm $REMOTE_FOLDER$REMOVE_MASK
EOF
done
echo $ARGS

if [[ "$ARGS" == "$RUN" ]];
then
for ((post=$POST_START; post<=$POST_END; post++))
do
ssh $USER@$POST_NET.$post << EOF
export DISPLAY=:0.0
$REMOTE_FOLDER$REMOTE_MAIN &
EOF
done
fi


