#!/bin/bash

LOCAL_FOLDER=../
USER=pi
POST_NET=10.8.0
POST_START=25
POST_END=25
REMOTE_FOLDER=/home/pi/python/
SYNC_FILE_CONFIG=config/tereshko3.cfg
REMOTE_MAIN=main.py

REMOVE_MASK=*.pyc
RUN=-r
ARGS=$1


for ((post=$POST_START; post<=$POST_END; post++))
do
    rsync -avzu -e ssh $USER@$POST_NET.$post:$REMOTE_FOLDER$SYNC_FILE_CONFIG $LOCAL_FOLDER$SYNC_FILE_CONFIG
    rsync -avzu --exclude={.tags,*.pyc,*.log,*.log.*,*.orig,*.conf,*.pickle} --progress --delete $LOCAL_FOLDER -e ssh $USER@$POST_NET.$post:$REMOTE_FOLDER
ssh $USER@$POST_NET.$post << EOF
killall -9 python
killall -9 omxplayer.bin
rm $REMOTE_FOLDER$REMOVE_MASK
EOF
done
echo $ARGS

if [[ "$ARGS" == "$RUN" ]];
then
for ((post=$POST_START; post<=$POST_END; post++))
do
ssh $USER@$POST_NET.$post << EOF
export DISPLAY=:0.0
$REMOTE_FOLDER$REMOTE_MAIN &
EOF
done
fi


